package com.sinopec.ldar.core.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sinopec.ldar.core.entity.PrdtCell;
import com.sinopec.ldar.core.entity.UserResult;

import com.sinopec.ldar.core.dao.PrdtCellDao;
import com.sinopec.ldar.core.dao.UserResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig prdtCellDaoConfig;
    private final DaoConfig userResultDaoConfig;

    private final PrdtCellDao prdtCellDao;
    private final UserResultDao userResultDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        prdtCellDaoConfig = daoConfigMap.get(PrdtCellDao.class).clone();
        prdtCellDaoConfig.initIdentityScope(type);

        userResultDaoConfig = daoConfigMap.get(UserResultDao.class).clone();
        userResultDaoConfig.initIdentityScope(type);

        prdtCellDao = new PrdtCellDao(prdtCellDaoConfig, this);
        userResultDao = new UserResultDao(userResultDaoConfig, this);

        registerDao(PrdtCell.class, prdtCellDao);
        registerDao(UserResult.class, userResultDao);
    }
    
    public void clear() {
        prdtCellDaoConfig.clearIdentityScope();
        userResultDaoConfig.clearIdentityScope();
    }

    public PrdtCellDao getPrdtCellDao() {
        return prdtCellDao;
    }

    public UserResultDao getUserResultDao() {
        return userResultDao;
    }

}
