package com.sinopec.ldar.core.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sinopec.ldar.core.entity.UserResult;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_RESULT".
*/
public class UserResultDao extends AbstractDao<UserResult, Integer> {

    public static final String TABLENAME = "USER_RESULT";

    /**
     * Properties of entity UserResult.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, int.class, "id", true, "ID");
        public final static Property UserId = new Property(1, double.class, "UserId", false, "USER_ID");
        public final static Property Name = new Property(2, String.class, "Name", false, "NAME");
        public final static Property Password = new Property(3, String.class, "Password", false, "PASSWORD");
        public final static Property PrdtCellId = new Property(4, double.class, "PrdtCellId", false, "PRDT_CELL_ID");
        public final static Property PrdtCellSname = new Property(5, String.class, "PrdtCellSname", false, "PRDT_CELL_SNAME");
    }


    public UserResultDao(DaoConfig config) {
        super(config);
    }
    
    public UserResultDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_RESULT\" (" + //
                "\"ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"USER_ID\" REAL NOT NULL ," + // 1: UserId
                "\"NAME\" TEXT," + // 2: Name
                "\"PASSWORD\" TEXT," + // 3: Password
                "\"PRDT_CELL_ID\" REAL NOT NULL ," + // 4: PrdtCellId
                "\"PRDT_CELL_SNAME\" TEXT);"); // 5: PrdtCellSname
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_RESULT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserResult entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindDouble(2, entity.getUserId());
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(3, Name);
        }
 
        String Password = entity.getPassword();
        if (Password != null) {
            stmt.bindString(4, Password);
        }
        stmt.bindDouble(5, entity.getPrdtCellId());
 
        String PrdtCellSname = entity.getPrdtCellSname();
        if (PrdtCellSname != null) {
            stmt.bindString(6, PrdtCellSname);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserResult entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindDouble(2, entity.getUserId());
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(3, Name);
        }
 
        String Password = entity.getPassword();
        if (Password != null) {
            stmt.bindString(4, Password);
        }
        stmt.bindDouble(5, entity.getPrdtCellId());
 
        String PrdtCellSname = entity.getPrdtCellSname();
        if (PrdtCellSname != null) {
            stmt.bindString(6, PrdtCellSname);
        }
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 0);
    }    

    @Override
    public UserResult readEntity(Cursor cursor, int offset) {
        UserResult entity = new UserResult( //
            cursor.getInt(offset + 0), // id
            cursor.getDouble(offset + 1), // UserId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Password
            cursor.getDouble(offset + 4), // PrdtCellId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // PrdtCellSname
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserResult entity, int offset) {
        entity.setId(cursor.getInt(offset + 0));
        entity.setUserId(cursor.getDouble(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPassword(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPrdtCellId(cursor.getDouble(offset + 4));
        entity.setPrdtCellSname(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Integer updateKeyAfterInsert(UserResult entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public Integer getKey(UserResult entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserResult entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
